services:
  server:
    container_name: dev-weave-server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: runner
#     volumes:
#       - ./server:/app
#       - /build/node_modules
    networks:
      - DevWeave
    ports:
      - "3000:3000"

  client:
    container_name: dev-weave-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: runner
#     volumes:
#       - ./client:/app
#       - /build/node_modules
    networks:
      - DevWeave
    ports:
      - "5173:5173"
    depends_on:
      - server

networks:
  DevWeave:
    driver: bridge
